### ISSUE TITLE
Add terrain visualization as a core concept

### ISSUE THREAD

**Issue by TaylorMutch** [VISTAS-IVES/pyvistas#22]

**Comment by nikmolnar** [comment]
I.e., terrain rendering will be handled by core, instead of by a plugin. Plugins will be able to rendering things on the terrain as textures, such as rasters as in the current terrain & color viz, or feature data, as in the current ENVISION plugin, or as 3D objects above the terrain (e.g., vector flow).

**Comment by TaylorMutch** [comment]
Closed #22.
